auth:
  type: DISABLED
kafka:
  clusters:
    - bootstrapServers: kafka:9092
      name: local
      properties: {}
      readOnly: false
      schemaRegistry: http://schema-registry:8085
rbac:
  roles: []
webclient: {}
